import logging
from pathlib import Path

import chromadb


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

CHROMA_PATH = "data/chroma"
COLLECTION_NAME = "rag_documents"


# ---------------------------------------------------------
# Logging
# ---------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s  %(message)s"
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------
# Vector Store
# ---------------------------------------------------------

class VectorStore:

    def __init__(
        self,
        persist_directory=CHROMA_PATH,
        collection_name=COLLECTION_NAME
    ):
        self.persist_directory = Path(
            persist_directory
        )

        self.collection_name = collection_name

        self.client = None
        self.collection = None

    # -----------------------------------------------------
    # Initialize Chroma
    # -----------------------------------------------------

    def load(self):
        """
        Initialize the persistent Chroma client
        and create/get the vector collection.
        """

        self.persist_directory.mkdir(
            parents=True,
            exist_ok=True
        )

        logger.info(
            f"Initializing Chroma at: "
            f"{self.persist_directory}"
        )

        self.client = chromadb.PersistentClient(
            path=str(self.persist_directory)
        )

        self.collection = (
            self.client.get_or_create_collection(
                name=self.collection_name,
                metadata={
                    "hnsw:space": "cosine"
                }
            )
        )

        logger.info(
            f"Chroma collection ready: "
            f"{self.collection_name}"
        )

        logger.info(
            f"Existing records: "
            f"{self.collection.count()}"
        )

        return self

    # -----------------------------------------------------
    # Ensure store is loaded
    # -----------------------------------------------------

    def _ensure_loaded(self):
        """
        Make sure the vector store has been initialized.
        """

        if self.collection is None:
            raise RuntimeError(
                "Vector store is not loaded. "
                "Call load() first."
            )

    # -----------------------------------------------------
    # Add records
    # -----------------------------------------------------

    def add(
        self,
        ids,
        embeddings,
        documents,
        metadatas
    ):
        """
        Store embeddings, documents and metadata
        in Chroma.

        Parameters
        ----------
        ids:
            Unique IDs for each chunk.

        embeddings:
            Embedding vectors generated by embedder.py.

        documents:
            Original chunk text.

        metadatas:
            Metadata associated with each chunk.
        """

        self._ensure_loaded()

        # -------------------------------------------------
        # Validate record counts
        # -------------------------------------------------

        if not (
            len(ids)
            == len(embeddings)
            == len(documents)
            == len(metadatas)
        ):
            raise ValueError(
                "ids, embeddings, documents, and "
                "metadatas must contain the same "
                "number of records"
            )

        if not ids:
            logger.warning(
                "No records provided to add()"
            )
            return

        logger.info(
            f"Adding {len(ids)} records to Chroma"
        )

        # -------------------------------------------------
        # Store records
        # -------------------------------------------------

        self.collection.add(
            ids=ids,
            embeddings=embeddings.tolist(),
            documents=documents,
            metadatas=metadatas
        )

        logger.info(
            "Records stored successfully"
        )

        logger.info(
            f"Total records: "
            f"{self.collection.count()}"
        )
    # -----------------------------------------------------
    # Vector similarity search
    # -----------------------------------------------------

    def search(
        self,
        query_embedding,
        top_k=5
    ):
        """
        Perform vector similarity search and return
        application-level results.

        The caller does not need to know Chroma's
        internal result format.
        """

        self._ensure_loaded()

        if top_k <= 0:
            raise ValueError(
                "top_k must be greater than 0"
            )

        # Do not request more results than exist.
        result_count = min(
            top_k,
            self.collection.count()
        )

        if result_count == 0:
            logger.warning(
                "Vector store is empty"
            )
            return []

        logger.info(
            f"Searching Chroma for top "
            f"{result_count} results"
        )

        # -------------------------------------------------
        # Chroma-specific operation
        # -------------------------------------------------

        results = self.collection.query(
            query_embeddings=[
                query_embedding.tolist()
            ],
            n_results=result_count
        )

        # -------------------------------------------------
        # Convert Chroma result into our own format
        # -------------------------------------------------

        formatted_results = []

        ids = results["ids"][0]
        documents = results["documents"][0]
        metadatas = results["metadatas"][0]
        distances = results["distances"][0]

        for i in range(len(ids)):

            formatted_results.append({
                "id": ids[i],
                "text": documents[i],
                "metadata": metadatas[i],
                "distance": distances[i]
            })

        logger.info(
            f"Retrieved {len(formatted_results)} results"
        )

        return formatted_results

    # -----------------------------------------------------
    # Count stored records
    # -----------------------------------------------------

    def count(self):
        """
        Return the number of records currently
        stored in Chroma.
        """

        self._ensure_loaded()

        return self.collection.count()